---
abstract: "a widget displaying a scrollable collection of\nitems"
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::More: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit-Widget-Scroller
provides:
  Tickit::Widget::Scroller:
    file: lib/Tickit/Widget/Scroller.pm
    version: 0.01
  Tickit::Widget::Scroller::Item::Text:
    file: lib/Tickit/Widget/Scroller/Item/Text.pm
    version: 0.01
requires:
  Tickit::Test: 0
  Tickit::Widget: 0.04
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
